apiVersions: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
        image: markodin/auth
        ports:
          - containerPort: 5000
        envFrom:
          - configMapRef:
              name: auth-configmap
          - secretRef:
              name: auth-secrets
